-- Script para criar a tabela ProdutosCulturas que está faltando no banco
-- Baseado na configuração do Entity Framework Core

CREATE TABLE IF NOT EXISTS public."ProdutosCulturas" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ProdutoId" integer NOT NULL,
    "CulturaId" integer NOT NULL,
    "Ativo" boolean NOT NULL DEFAULT true,
    "Observacoes" character varying(500),
    "DataCriacao" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DataAtualizacao" timestamp with time zone,
    
    CONSTRAINT "PK_ProdutosCulturas" PRIMARY KEY ("Id"),
    
    -- Foreign Key para Produto
    CONSTRAINT "FK_ProdutosCulturas_Produto_ProdutoId" 
        FOREIGN KEY ("ProdutoId") 
        REFERENCES public."Produto" ("Id") 
        ON DELETE CASCADE,
    
    -- Foreign Key para Cultura
    CONSTRAINT "FK_ProdutosCulturas_Cultura_CulturaId" 
        FOREIGN KEY ("CulturaId") 
        REFERENCES public."Cultura" ("Id") 
        ON DELETE CASCADE
);

-- Índices conforme configuração do EF Core
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProdutosCulturas_ProdutoId_CulturaId" 
    ON public."ProdutosCulturas" ("ProdutoId", "CulturaId");

CREATE INDEX IF NOT EXISTS "IX_ProdutosCulturas_ProdutoId" 
    ON public."ProdutosCulturas" ("ProdutoId");

CREATE INDEX IF NOT EXISTS "IX_ProdutosCulturas_CulturaId" 
    ON public."ProdutosCulturas" ("CulturaId");

CREATE INDEX IF NOT EXISTS "IX_ProdutosCulturas_Ativo" 
    ON public."ProdutosCulturas" ("Ativo");

-- Comentários para documentação
COMMENT ON TABLE public."ProdutosCulturas" IS 'Tabela de relacionamento entre Produtos e Culturas';
COMMENT ON COLUMN public."ProdutosCulturas"."Id" IS 'Identificador único da associação';
COMMENT ON COLUMN public."ProdutosCulturas"."ProdutoId" IS 'ID do produto associado';
COMMENT ON COLUMN public."ProdutosCulturas"."CulturaId" IS 'ID da cultura associada';
COMMENT ON COLUMN public."ProdutosCulturas"."Ativo" IS 'Indica se a associação está ativa';
COMMENT ON COLUMN public."ProdutosCulturas"."Observacoes" IS 'Observações sobre a compatibilidade produto-cultura';
COMMENT ON COLUMN public."ProdutosCulturas"."DataCriacao" IS 'Data de criação do registro';
COMMENT ON COLUMN public."ProdutosCulturas"."DataAtualizacao" IS 'Data da última atualização do registro';